global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: "api"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["traefik:80"]
